project:
  type: book
  output-dir: _book
  resources:
    - "webex.js"
  preview:
    port: 9123
    host: 127.0.0.1
    watch-inputs: true
  
book:
  title: "Understanding Uncertainty"
  subtitle: "An Introduction to Probability and Statistics"
  author: "Dylan Spicker"
  original-date: "12/30/2023"
  date: "09/03/2024"
  downloads: ["pdf"]
  chapters:
    - index.qmd
    - part: "Part 1: Probability"
      chapters:
      - notes/chapter1.qmd
      - notes/chapter2.qmd
      - notes/chapter3.qmd
      - notes/chapter4.qmd
      - notes/chapter5.qmd
      - notes/chapter6.qmd
      - notes/chapter7.qmd
      - notes/chapter8.qmd
      - notes/chapter9.qmd
    - part: "Part 2: Statistics"
      chapters:
      - notes/chapter10.qmd
      - notes/chapter11.qmd
      - notes/chapter12.qmd
      - notes/chapter13.qmd
      - notes/chapter14.qmd
      - notes/chapter15.qmd
      - notes/chapter16.qmd
      - notes/chapter17.qmd
      - notes/chapter18.qmd
      - notes/chapter19.qmd
      - notes/chapter20.qmd
engine: knitr

filters: 
- webr

bibliography: references.bib

format:
  html:
    lightbox: true
    theme: 
    - cosmo
    - custom.scss
    include-after-body: 
      text: |
        <script type="application/javascript" src="/webex.js"></script>
    code-annotations: select
    default-image-extension: svg
  pdf:
    documentclass: scrreprt
    default-image-extension: png
    fig-pos: H
    include-in-header: macros.tex

crossref:
  custom:
    - kind: float
      reference-prefix: Practice Problem
      latex-env: prac
      key: prac
prac-cap-location: top


# comments:
#   hypothesis: 
#     theme: classic
#     enableExperimentalNewNoteButton: true 
#     showHighlights: whenSidebarOpen

execute:
  eval: true

knitr:
  opts_chunk: 
    collapse: true
    results: hold

fig-cap-location: top