```{r data generation, echo = FALSE, results = "hide"}
library(ggplot2)

n <- 100000

d <- list(rnorm(n), rexp(n, rate = 1) - 1, -1 * (rexp(n, rate = 1) - 1), rt(n, df = 5), runif(n, -3, 3), rbeta(n, 2, 5))

d[[3]] <- (d[[3]] - min(d[[3]]))/(max(d[[3]]) - min(d[[3]])) * (max(d[[2]]) - min(d[[2]])) + min(d[[2]])

idxs <- sample(1:length(d), 4)

show_which <- sample(0:1, 1)
show_which_id <- sample(idxs, 1)
sol <- c(FALSE, FALSE, FALSE, FALSE)
sol[which(idxs == show_which_id)] <- TRUE

if(show_which == 0) {
    plot_type <- "histogram"
    
    plot_to_show <- ggplot(data.frame(x=d[[show_which_id]]), aes(x=x)) + geom_histogram(bins=30) + 
                      theme_minimal() + theme(axis.text.y=element_blank(), plot.background=element_blank(), panel.background=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank()) + 
                      ggtitle("Histogram")

    # Show Boxplots + 1 Histogram
    p1 <- ggplot(data.frame(x=d[[idxs[[1]]]]), aes(y=x)) + geom_boxplot() + theme_minimal() + theme(axis.text.x=element_blank(), plot.background=element_blank(), panel.background=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank()) + ggtitle("(A)")
    p2 <- ggplot(data.frame(x=d[[idxs[[2]]]]), aes(y=x)) + geom_boxplot() + theme_minimal() + theme(axis.text.x=element_blank(), plot.background=element_blank(), panel.background=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank()) + ggtitle("(B)")
    p3 <- ggplot(data.frame(x=d[[idxs[[3]]]]), aes(y=x)) + geom_boxplot() + theme_minimal() + theme(axis.text.x=element_blank(), plot.background=element_blank(), panel.background=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank()) + ggtitle("(C)")
    p4 <- ggplot(data.frame(x=d[[idxs[[4]]]]), aes(y=x)) + geom_boxplot() + theme_minimal() + theme(axis.text.x=element_blank(), plot.background=element_blank(), panel.background=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank()) + ggtitle("(D)")
} else {

    plot_type <- "boxplot"

    plot_to_show <- ggplot(data.frame(x=d[[show_which_id]]), aes(y=x)) + geom_boxplot() + theme_minimal() + theme(axis.text.x=element_blank(), plot.background=element_blank(), panel.background=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank()) + ggtitle("Boxplot")

    p1 <- ggplot(data.frame(x=d[[idxs[1]]]), aes(x=x)) + geom_histogram(bins=30) + theme_minimal() + theme(axis.text.y=element_blank(), plot.background=element_blank(), panel.background=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank()) + ggtitle("(A)")
    p2 <- ggplot(data.frame(x=d[[idxs[2]]]), aes(x=x)) + geom_histogram(bins=30) + theme_minimal() + theme(axis.text.y=element_blank(), plot.background=element_blank(), panel.background=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank()) + ggtitle("(B)")
    p3 <- ggplot(data.frame(x=d[[idxs[3]]]), aes(x=x)) + geom_histogram(bins=30) + theme_minimal() + theme(axis.text.y=element_blank(), plot.background=element_blank(), panel.background=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank()) + ggtitle("(C)")
    p4 <- ggplot(data.frame(x=d[[idxs[4]]]), aes(x=x)) + geom_histogram(bins=30) + theme_minimal() + theme(axis.text.y=element_blank(), plot.background=element_blank(), panel.background=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank()) + ggtitle("(D)")
}


id <- sprintf("%010d", sample(0:1000000000, 1))

```

Question
========
Consider the following `r plot_type`.

```{r main_plot, warning = FALSE, echo = FALSE, results = "hide", fig.height = 4, fig.width = 6, fig.path = "", fig.cap = ""}
plot_to_show
```

Which of the following shows the same data? 

```{r subplots, warning = FALSE, echo = FALSE, results = "hide", fig.height = 4, fig.width = 10, fig.path = "", fig.cap = ""}
gridExtra::grid.arrange(p1, p2, p3, p4, nrow = 1)
```

(Question ID: *`r id`*)

Answerlist
----------
* (A)
* (B)
* (C)
* (D)

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(sol)`
exname: Histogram and Boxplot Matching