```{r data generation, echo = FALSE, results = "hide"}

avg <- sample(40:180, 1)
n <- sample(35:100, 1)
sd <- round(runif(1, 3, 25), 2)
alpha <- round(runif(1, 0.01, 0.2), 2)
crit <- qt(1-alpha/2, df = n-1)

if(sample(c(0,1),1) == 0) {
    # Reject
    val <- sample(c(-1, 1), 1) * runif(1, 1.1 * crit, 2 * crit)
} else {
    # Fail to Reject
    val <- sample(c(-1, 1), 1) * runif(1, 0.2 * crit, 0.85 * crit)
}

mean <- round(val * sd/sqrt(n) + avg,1)

ans1 <- (mean - avg)/(sd / sqrt(n))
ans2 <- 2 * pt(-abs(ans1), df = n-1)
ans3 <- c(ans2 >= alpha, ans2 < alpha)

id <- sprintf("%010d", sample(0:1000000000, 1))

```

Question
========
A biologist is studying the average lifespan of a particular species of beetle. Based on previous research, the average lifespan of these beetles is known to be `r avg` days. The biologist suspects that environmental changes in a specific region might be affecting the beetles' lifespan. They observe a sample of `r n` beetles from the specific region, finding an average life span of `r mean` days with a standard deviation of `r sd` days. 

a. What is the relevant value of the test statistic for testing the null hypothesis? ##ANSWER1##
a. What is the $p$-value calculated when running this hypothesis test? ##ANSWER2##
c. What is the conclusion from the hypothesis test, if $\alpha = `r alpha`$? 

##ANSWER3##

Question ID: *`r id`*

Answerlist
------------
* Based on the results, we can reject the null hypothesis.
* Based on the results, we fail to reject the null hypothesis. 


Meta-information
================
extype: cloze
exsolution: `r fmt(ans1, 3)`|`r fmt(ans2, 3)`|`r mchoice2string(ans3)`
exclozetype: num|num|schoice
exname: CriticalValueTes
extol: 0.01