```{r data generation, echo = FALSE, results = "hide"}

prizes <- sample(c(0.25, 0.5, 0.75, 1), 3, TRUE) * 10 ^ sort(sample(1:6, 3))
probs <- pmin(pmax(sort(diff(sort(round(runif(4, 0, 1), 3))), decreasing = TRUE), 0.001), 0.15)

EX <- sum(prizes * probs)
var <- sum(prizes^2 * probs) - EX^2

fair_ind <- sample(1:3, 1)
if(fair_ind == 1) {
    cost_to_play <- EX
} else if(fair_ind == 2) {
    cost_to_play <- sample(floor(0.5 * EX):floor(EX), 1)
} else {
    cost_to_play <- sample(ceiling(EX):(2*ceiling(EX)), 1)
}

ans1 <- EX
ans2 <- EX - cost_to_play
ans3 <- var
ans4 <- sqrt(var)

id <- sprintf("%010d", sample(0:1000000000, 1))

```

Question
========

A lottery is proposed that would pay players a prize of \$`r format(prizes[1], big.mark = ",", scientific=FALSE, nsmall=2)` with probability `r probs[1]`, a prize of \$`r format(prizes[2], big.mark = ",", scientific=FALSE, nsmall=2)` with probability `r probs[2]`, and a prize of \$`r format(prizes[3], big.mark = ",", scientific=FALSE, nsmall=2)` with probability `r probs[3]`.

a. If the game is to be fair, how much should it cost to play this lottery? ##ANSWER1##
a. Suppose that a ticket of playing this lottery costs \$`r format(cost_to_play, scientific=FALSE, nsmall=2)`. What is the expected value of a single lottery ticket? ##ANSWER2##
c. What is the variance of the payout from a single lottery ticket? ##ANSWER3##
d. What is the standard deviation of the total earnings from a single lottery ticket, if it costs \$`r format(cost_to_play, scientific=FALSE, nsmall=2)`? ##ANSWER4##

Question ID: *`r id`*

Meta-information
================
extype: cloze
exsolution: `r fmt(ans1, 3)`|`r fmt(ans2, 3)`|`r fmt(ans3, 3)`|`r fmt(ans4, 3)`
exclozetype: num|num|num|num
exname: ExpectedValueAndVarBasic
extol: 0.01|0.01|1|0.1