```{r data generation, echo = FALSE, results = "hide"}

type <- sample(c("discrete", "continuous"), 1)

sol <- c(rep(TRUE, 13), rep(FALSE, 7))
if(type == "continuous") sol <- !sol 

id <- sprintf("%010d", sample(0:1000000000, 1))
```

Question
========
Which of the following is a `r type` random variable?

(Question ID: *`r id`*)

Answerlist
------------
* In a survey, the number of siblings each participant has is recorded.
* The number of cars passing through a toll booth in an hour.
* In a casino game, the amount of money won or lost on a single bet.
* In a classroom, the number of students who own a laptop.
* When flipping a coin, the number of heads obtained in 10 flips.
* The number of emails received per day.
* In a factory, the number of defective products in a batch.
* When selecting a card from a standard deck, the card’s face value.
* The age (in years) at which individuals first learn to ride a bicycle.
* The number of customers entering a store in one hour.
* The number of books a person reads in a month.
* When rolling two dice, the sum of the numbers rolled.
* The number of text messages sent in a day.
* A thermometer measures temperature in degrees Celsius.
* The weight of apples harvested from an orchard.
* The time it takes for a light bulb to burn out.
* The height of students in a class.
* The distance traveled by a car in a specific time interval.
* In a soccer match, the time it takes for the first goal to be scored.
* The volume of water in a reservoir.

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(sol)`
exshuffle: 5
exname: IdentifyDiscreteVersusContinuous