```{r data generation, echo = FALSE, results = "hide"}

# Question Texts 

n <- sample(10:100, 1)
m <- sample(10:100, 1)

Xbar <- round(runif(1, -100, 100), 2)
Ybar <- round(runif(1, -100, 100), 2)

sdX <- round(runif(1, 1, 10), 2)

direction <- sample(1:3, 1)
conclusion <- sample(0:1, 1)

alpha <- round(runif(1, 0.01, 0.2), 2)

if(conclusion == 0) {
    p_val <- round(runif(1, 0.001, alpha - 0.005), 3)
} else {
    p_val <- round(runif(1, 0.001 + alpha, 0.9), 3)
}

ratio_type <- sample(1:3, 1)

if(direction == 1) {
    symbol <- "$ is really equal to $"
    crit <- qf(sample(c(p_val/2, 1-p_val/2), 1), df1 = n-1, df2 = m-1)
    p_val_calc <- function(f) { 2 * min(pf(f, df1 = n-1, df2 = m-1), 1 - pf(f, df1 = n-1, df2 = m-1)) }
} else if(direction == 2) {
    symbol <- ">"
    crit <- qf(1-p_val, df1 = n-1, df2 = m-1)
    p_val_calc <- function(f) { 1-pf(f, df1 = n-1, df2 = m-1) }
} else if(direction == 3) {
    symbol <- "<"
    crit <- qf(p_val, df1 = n-1, df2 = m-1)
    p_val_calc <- function(f) { pf(f, df1 = n-1, df2 = m-1) }
}

if(ratio_type == 1) {
    r <- 1
    statement <- paste0("$\\sigma_X^2",symbol,"\\sigma_Y^2$")
} else if(ratio_type == 2) { 
    r <- round(runif(1,0.5, 0.99), 2)
    statement <- paste0("$", r, "\\sigma_X^2",symbol,"\\sigma_Y^2$")
} else {
    r <- round(runif(1, 1.1,3), 2)
    statement <- paste0("$", r, "\\sigma_X^2",symbol,"\\sigma_Y^2$")
}

sdY <- round(sqrt(r * sdX^2 / crit), 2)

test_stat <- r * sdX^2 / sdY^2
actual_p <- p_val_calc(test_stat)



ans1 <- test_stat
ans2 <- actual_p
ans3 <- c(ans2 <= alpha, ans2 > alpha)


id <- sprintf("%010d", sample(0:1000000000, 1))

```

Question
========

Data are collected from two independent, normally distributed populations. From the first population, a sample of size `r n` is taken, observing a sample mean of `r Xbar` and a standard deviation of `r sdX`. From the second population, a sample of size `r m` is taken, observing a sample mean of `r Ybar` and a standard deviation of `r sdY`. There is a desire to determine whether `r statement`. 

Test the corresponding hypothesis with a significance level of `r alpha`.

a. What is the value of the test statistic used to test this hypothesis? ##ANSWER1##
b. What is the $p$-value resulting from this hypothesis test? ##ANSWER2##
d. What is the conclusion from the hypothesis test?

##ANSWER3##

Question ID: *`r id`*

Answerlist
------------
* Based on the results, we can reject the null hypothesis.
* Based on the results, we fail to reject the null hypothesis. 



Meta-information
================
extype: cloze
exsolution: `r fmt(ans1, 3)`|`r fmt(ans2, 3)`|`r mchoice2string(ans3)`
exclozetype: num|num|schoice
exname: TwoSampleFTestForVariances
extol: 0.01